version: '3.9'
services:

  backend: 
    container_name: "backend"
    build: 
      context: "backend"
      dockerfile: "Dockerfile"
    restart: "on-failure"
    ports:
      - "4000:3001"
    env_file: 
      - backend/.env
    depends_on:
      - database
    networks:
      - backend

  frontend: 
    container_name: "frontend"
    build: 
      context: "frontend"
      dockerfile: "Dockerfile"
    restart: "on-failure"
    ports: 
      - "8080:80"
    depends_on:
      - backend
    networks:
      - frontend

  database:
    container_name: "postgres"
    volumes:
      - postgres_data:/data/database
    image: "postgres"
    restart: "on-failure"
    env_file: 
      - backend/.env
    networks:
      - backend

  adminer:
    container_name: "adminer"
    image: "adminer"
    restart: "on-failure"
    ports: 
      - "8081:8080"
    depends_on:
      - database

volumes:
  postgres_data:

networks:
  frontend:
  backend: 